---
# Test setup.
scanPath: /pathToDatasetFolder/sipailou-livox-kitti/sequences/00/velodyne/
posePath: /pathToDatasetFolder/sipailou-livox-kitti/sequences/00/poses.txt
startScan: 1
endScan: 2648
minRange: 3
maxRange: 50
outputFile: false
scanNumsToPrint: []
outputFileName:
outputLabels: true
outputLabelFolder: /saveFolderPath/results/labels/sipailou_00/

# Configuration parameters.
voxelSize: 0.2
occupancySigma: 0.2
freeSigma: 0.2
beliefThreshold: 0.99
convSize: 5
localWindowSize: 3
globalWindowSize: 300
minOtsu: 3