---
# Test setup.
scanPath: /pathToDatasetFolder/sipailou-livox-kitti/sequences/00/velodyne/
posePath: /pathToDatasetFolder/sipailou-livox-kitti/sequences/00/poses.txt
minRange: 3
maxRange: 50
outputFile: false
scanNumsToPrint: []
outputFileName:
outputLabels: true
outputLabelFolder: /saveFolderPath/results/labels/sipailou_00/

# Configuration parameters.
voxelSize: 0.25
occupancySigma: 0.25
beliefThreshold: 0.99
convSize: 5
localWindowSize: 3
globalWindowSize: 300
dynamicRegionWindowSize: 100
numScansDelay: 0
minOtsu: 3