---
# File paths
scanPath: /pathToDatasetFolder/station/sequence_2/binFiles/
posePath: /pathToHmmMosFolder/benchmarking/datsetPoses/DOALS/station_seq2.txt
minRange: 0.5
maxRange: 20
outputFile: true
scanNumsToPrint: [149, 319, 489, 659, 829, 999, 1169, 1339, 1509, 1679]
outputFileName: /saveFolderPath/results/test_seq8
outputLabels: false
outputLabelFolder: 

# Configuration parameters.
voxelSize: 0.2
occupancySigma: 0.2
beliefThreshold: 0.99
convSize: 5
localWindowSize: 3
globalWindowSize: 300
dynamicRegionWindowSize: 100
numScansDelay: 0
minOtsu: 3