---
# File paths
scanPath: /pathToDatasetFolder/niederdorf/sequence_1/binFiles/
posePath: /pathToDatasetFolder/niederdorf/sequence_1/poses.txt
minRange: 0.5
maxRange: 20
outputFile: true
scanNumsToPrint: [76, 256, 436, 616, 796, 976, 1156, 1336, 1516, 1696]
outputFileName: /saveFolderPath/results/test_seq3
outputLabels: false
outputLabelFolder: 

# Configuration parameters.
voxelSize: 0.25
occupancySigma: 0.25
beliefThreshold: 0.99
convSize: 5
localWindowSize: 5
globalWindowSize: 300
minOtsu: 3
