---
# File paths
scanPath: /pathToDatasetFolder/station/sequence_1/binFiles/
posePath: /pathToHmmMosFolder/benchmarking/datsetPoses/DOALS/station_seq1.txt
minRange: 0.5
maxRange: 20
outputFile: true
scanNumsToPrint: [37, 149, 349, 549, 749, 949, 1149, 1349, 1549, 1749]
outputFileName: /saveFolderPath/results/test_seq7
outputLabels: false
outputLabelFolder: 

# Configuration parameters.
voxelSize: 0.2
occupancySigma: 0.2
beliefThreshold: 0.99
convSize: 5
localWindowSize: 3
globalWindowSize: 300
dynamicRegionWindowSize: 100
numScansDelay: 0
minOtsu: 3