---
# File paths
scanPath: /pathToDatasetFolder/niederdorf/sequence_2/binFiles/
posePath: /pathToDatasetFolder/niederdorf/sequence_2/poses.txt
minRange: 0.5
maxRange: 20
outputFile: true
scanNumsToPrint: [139, 299, 459, 619, 779, 939, 1099, 1259, 1419, 1579]
outputFileName: /saveFolderPath/results/test_seq4
outputLabels: false
outputLabelFolder: 

# Configuration parameters.
voxelSize: 0.25
occupancySigma: 0.25
beliefThreshold: 0.99
convSize: 5
localWindowSize: 5
globalWindowSize: 300
minOtsu: 3
