---
# File paths
scanPath: /pathToDatasetFolder/hauptgebaeude/sequence_2/binFiles/
posePath: /pathToDatasetFolder/hauptgebaeude/sequence_2/poses.txt
minRange: 0.5
maxRange: 20
outputFile: true
scanNumsToPrint: [129, 279, 429, 579, 729, 879, 1029, 1179, 1329, 1479]
outputFileName: /saveFolderPath/results/test_seq2
outputLabels: false
outputLabelFolder: 

# Configuration parameters.
voxelSize: 0.25
occupancySigma: 0.25
beliefThreshold: 0.99
convSize: 5
localWindowSize: 5
globalWindowSize: 300
minOtsu: 3
