---
# File paths
scanPath: /pathToDatasetFolder/niederdorf/sequence_2/binFiles/
posePath: /pathToHmmMosFolder/benchmarking/datsetPoses/DOALS/niederdorf_seq2.txt
minRange: 0.5
maxRange: 20
outputFile: true
scanNumsToPrint: [139, 299, 459, 619, 779, 939, 1099, 1259, 1419, 1579]
outputFileName: /saveFolderPath/results/test_seq4
outputLabels: false
outputLabelFolder: 

# Configuration parameters.
voxelSize: 0.2
occupancySigma: 0.2
beliefThreshold: 0.99
convSize: 5
localWindowSize: 3
globalWindowSize: 300
dynamicRegionWindowSize: 100
numScansDelay: 0
minOtsu: 3