---
# File paths
scanPath: /pathToDatasetFolder/hauptgebaeude/sequence_2/binFiles/
posePath: /pathToHmmMosFolder/benchmarking/datsetPoses/DOALS/hauptgebaeude_seq2.txt
minRange: 0.5
maxRange: 20
outputFile: true
scanNumsToPrint: [129, 279, 429, 579, 729, 879, 1029, 1179, 1329, 1479]
outputFileName: /saveFolderPath/results/test_seq2
outputLabels: false
outputLabelFolder: 

# Configuration parameters.
voxelSize: 0.2
occupancySigma: 0.2
beliefThreshold: 0.99
convSize: 5
localWindowSize: 3
globalWindowSize: 300
dynamicRegionWindowSize: 100
numScansDelay: 0
minOtsu: 3