---
# File paths
scanPath: /pathToDatasetFolder/station/sequence_2/binFiles/
posePath: /pathToDatasetFolder/station/sequence_2/poses.txt
startScan: 1
endScan: 1758
minRange: 0.5
maxRange: 120
outputFile: true
scanNumsToPrint: [149, 319, 489, 659, 829, 999, 1169, 1339, 1509, 1679]
outputFileName: /saveFolderPath/results/test_seq8
outputLabels: false
outputLabelFolder: 

# Configuration parameters
voxelSize: 0.2
occupancySigma: 0.2
freeSigma: 0.2
beliefThreshold: 0.99
convSize: 5
localWindowSize: 3
minOtsu: 3
globalWindowSize: 300