---
# File paths
scanPath: /pathToDatasetFolder/shopville/sequence_1/binFiles/
posePath: //pathToDatasetFolder/shopville/sequence_1/binFiles/poses.txt
startScan: 1
endScan: 1068
minRange: 0.5
maxRange: 20
outputFile: true
scanNumsToPrint: [79, 179, 279, 379, 479, 579, 679, 779, 879, 979]
outputFileName: /saveFolderPath/results/test_seq5
outputLabels: false
outputLabelFolder: 

# Configuration parameters
voxelSize: 0.2
occupancySigma: 0.2
freeSigma: 0.2
beliefThreshold: 0.99
convSize: 5
localWindowSize: 3
minOtsu: 3
globalWindowSize: 300