---
# File paths
scanPath: /pathToDatasetFolder/shopville/sequence_2/binFiles/
posePath: /pathToDatasetFolder/shopville/sequence_2/binFiles/poses.txt
minRange: 0.5
maxRange: 20
outputFile: true
scanNumsToPrint: [199, 399, 527, 599, 799, 999, 1199, 1399, 1599, 1799]
outputFileName: /saveFolderPath/results/test_seq6
outputLabels: false
outputLabelFolder: 

# Configuration parameters.
voxelSize: 0.25
occupancySigma: 0.25
beliefThreshold: 0.99
convSize: 5
localWindowSize: 5
globalWindowSize: 300
minOtsu: 3
