---
# File paths
scanPath: /pathToDatasetFolder/hauptgebaeude/sequence_1/binFiles/
posePath: /pathToDatasetFolder/hauptgebaeude/sequence_1/poses.txt
minRange: 0.5
maxRange: 20
outputFile: true
scanNumsToPrint: [89, 199, 309, 419, 529, 639, 749, 859, 969, 1079]
outputFileName: /saveFolderPath/results/test_seq1
outputLabels: false
outputLabelFolder: 

# Configuration parameters.
voxelSize: 0.25
occupancySigma: 0.25
beliefThreshold: 0.99
convSize: 5
localWindowSize: 5
globalWindowSize: 300
minOtsu: 3
