---
# File paths
scanPath: /pathToDatasetFolder/station/sequence_2/binFiles/
posePath: /pathToDatasetFolder/station/sequence_2/poses.txt
minRange: 0.5
maxRange: 20
outputFile: true
scanNumsToPrint: [149, 319, 489, 659, 829, 999, 1169, 1339, 1509, 1679]
outputFileName: /saveFolderPath/results/test_seq8
outputLabels: false
outputLabelFolder: 

# Configuration parameters.
voxelSize: 0.25
occupancySigma: 0.25
beliefThreshold: 0.99
convSize: 5
localWindowSize: 5
globalWindowSize: 300
minOtsu: 3
