---
# File paths
scanPath: /pathToDatasetFolder/station/sequence_1/binFiles/
posePath: /pathToDatasetFolder/station/sequence_1/binFiles/poses.txt
minRange: 0.5
maxRange: 20
outputFile: true
scanNumsToPrint: [37, 149, 349, 549, 749, 949, 1149, 1349, 1549, 1749]
outputFileName: /saveFolderPath/results/test_seq7
outputLabels: false
outputLabelFolder: 

# Configuration parameters.
voxelSize: 0.25
occupancySigma: 0.25
beliefThreshold: 0.99
convSize: 5
localWindowSize: 5
globalWindowSize: 300
minOtsu: 3
