---
# File paths
scanPath: /pathToDatasetFolder/niederdorf/sequence_1/binFiles/
posePath: /pathToDatasetFolder/niederdorf/sequence_1/poses.txt
startScan: 1
endScan: 1768
minRange: 0.5
maxRange: 120
outputFile: true
scanNumsToPrint: [76, 256, 436, 616, 796, 976, 1156, 1336, 1516, 1696]
outputFileName: /saveFolderPath/results/test_seq3
outputLabels: false
outputLabelFolder: 

# Configuration parameters
voxelSize: 0.2
occupancySigma: 0.2
freeSigma: 0.2
beliefThreshold: 0.99
convSize: 5
localWindowSize: 3
minOtsu: 3
globalWindowSize: 300