---
# File paths
scanPath: /pathToDatasetFolder/KAIST05/Deskewed_LiDAR/Aeva/velodyne/
posePath: /pathToHmmMosFolder/benchmarking/datsetPoses/HeLiMOS/aeva_poses.txt
minRange: 1.5
maxRange: 50
outputFile: false
scanNumsToPrint: []
outputFileName:
outputLabels: true
outputLabelFolder: /pathToDatasetFolder/KAIST05/Deskewed_LiDAR/Aeva/predictions/

# Configuration parameters.
voxelSize: 0.25
occupancySigma: 0.25
beliefThreshold: 0.99
convSize: 5
localWindowSize: 3
globalWindowSize: 300
dynamicRegionWindowSize: 100
numScansDelay: 0
minOtsu: 3