---
# Test setup.
scanPath: /pathToDatasetFolder/LiDAR-MOS/sequences/03/velodyne/
posePath: /pathToDatasetFolder/poses.txt
startScan: 1
endScan: 500
minRange: 0.5
maxRange: 120
outputFile: false
scanNumsToPrint: []
outputFileName:
outputLabels: true
outputLabelFolder: /saveFolderPath/results/labels/apollo_03/ 

# Configuration parameters.
voxelSize: 0.2
occupancySigma: 0.2
freeSigma: 0.2
beliefThreshold: 0.99
convSize: 5
localWindowSize: 3
minOtsu: 3
globalWindowSize: 300