---
# File paths
scanPath: /media/vb/Gift/DOALS/processed/hauptgebaeude/sequence_2/binFiles/
posePath: /home/vb/Documents/public_repositories/SiMpLE/build/seq2_deskewed
startScan: 2
endScan: 1488
minRange: 0.5
maxRange: 120
outputFile: true
scanNumsToPrint: [129, 279, 429, 579, 729, 879, 1029, 1179, 1329, 1479]
outputFileName: /home/vb/Documents/public_repositories/QCD_MOS/results/test_seq2
outputLabels: false
outputLabelFolder: 

# Configuration parameters
voxelSize: 0.2
occupancySigma: 0.2
freeSigma: 0.2
beliefThreshold: 0.3
convSize: 5
localWindowSize: 3
globalWindowSize: 300
offset: 0