---
# File paths
scanPath: /media/vb/Gift/DOALS/processed/hauptgebaeude/sequence_1/binFiles/
posePath: /home/vb/Documents/public_repositories/SiMpLE/build/seq1_deskewed
startScan: 2
endScan: 1079
minRange: 0.5
maxRange: 120
outputFile: true
scanNumsToPrint: [89, 199, 309, 419, 529, 639, 749, 859, 969, 1079]
outputFileName: /home/vb/Documents/public_repositories/QCD_MOS/results/test_seq1
outputLabels: false
outputLabelFolder: 

# Configuration parameters
voxelSize: 0.2
occupancySigma: 0.2
freeSigma: 0.2
beliefThreshold: 0.3
convSize: 5
localWindowSize: 3
globalWindowSize: 300
offset: 0