---
# File paths
scanPath: /home/vb/Documents/PhD/projects/changePointDetectionV3/src/rosbagProcessing/indoor/binFiles/
posePath: /home/vb/Documents/public_repositories/SiMpLE/build/seq_indoor
startScan: 1
endScan: 267
minRange: 0.5
maxRange: 100
outputFile: false
scanNumsToPrint: []
outputFileName: 
outputLabels: true
outputLabelFolder: /home/vb/Documents/PhD/projects/changePointDetectionV7/cpp/results/labels/test_seqIndoor/

# Configuration parameters
voxelSize: 0.2
occupancySigma: 0.2
freeSigma: 0.3
beliefThreshold: 0.5
convSize: 3
localWindowSize: 5
globalWindowSize: 500
offset: 0