---
# File paths
scanPath: /media/vb/Gift/DOALS/processed/shopville/sequence_2/binFiles/
posePath: /home/vb/Documents/public_repositories/SiMpLE/build/seq6_deskewed
startScan: 2
endScan: 1988
minRange: 0.5
maxRange: 120
outputFile: true
scanNumsToPrint: [199, 399, 527, 599, 799, 999, 1199, 1399, 1599, 1799]
outputFileName: /home/vb/Documents/public_repositories/QCD_MOS/results/test_seq6
outputLabels: false
outputLabelFolder: 

# Configuration parameters
voxelSize: 0.2
occupancySigma: 0.2
freeSigma: 0.2
beliefThreshold: 0.3
convSize: 5
localWindowSize: 3
globalWindowSize: 300
offset: 0