---
# Test setup.
scanPath: /home/vb/Documents/PhD/datasets/Kitti/sequences/01/velodyne/
# scanPath: /home/vb/Documents/PhD/datasets/Kitti/raw_data/2011_09_30/2011_09_30_drive_0027_sync/velodyne_points/data/
# posePath: /home/vb/Documents/PhD/datasets/Kitti/sumaPosesSensorFrame/01/.txt
posePath: /home/vb/Documents/public_repositories/SiMpLE/sampleResults/KITTI/simpleOutputs/offline/01
startScan: 1
endScan: 1101
minRange: 3
maxRange: 120
outputFile: false
scanNumsToPrint: []
outputFileName:
outputLabels: true
outputLabelFolder: /home/vb/Documents/PhD/projects/changePointDetectionV7Conc2/results/labels/01/

# Configuration parameters.
voxelSize: 0.2
occupancySigma: 0.3
freeSigma: 0.3
beliefThreshold: 0.9
convSize: 5
localWindowSize: 3
globalWindowSize: 300
offset: 0