---
# File paths
scanPath: /media/vb/Gift/DOALS/processed/shopville/sequence_1/binFiles/
posePath: /home/vb/Documents/public_repositories/SiMpLE/build/seq5_deskewed
startScan: 1
endScan: 1068
minRange: 0.5
maxRange: 120
outputFile: true
scanNumsToPrint: [79, 179, 279, 379, 479, 579, 679, 779, 879, 979]
outputFileName: /home/vb/Documents/public_repositories/QCD_MOS/results/test_seq5
outputLabels: false
outputLabelFolder: 

# Configuration parameters
voxelSize: 0.2
occupancySigma: 0.2
freeSigma: 0.2
beliefThreshold: 0.3
convSize: 5
localWindowSize: 3
globalWindowSize: 300
offset: 0