---
# Test setup.
scanPath: /home/vb/Documents/PhD/datasets/Kitti/sequences/01/velodyne/
posePath: /home/vb/Documents/PhD/datasets/Kitti/sumaPosesSensorFrame/01.txt
startScan: 1
endScan: 1101
minRange: 3
maxRange: 120
outputFile: false
scanNumsToPrint: []
outputFileName: /home/vb/Documents/PhD/projects/changePointDetectionV7/cpp/results/test_KITTI
outputLabels: true
outputLabelFolder: /home/vb/Documents/PhD/projects/changePointDetectionV7/cpp/results/labels/01/

# Configuration parameters.
voxelSize: 0.5
occupancySigma: 0.5
freeSigma: 0.5
beliefThreshold: 0.5
convSize: 5
localWindowSize: 5
globalWindowSize: 10
offset: 0