---
# Test setup.
scanPath: /media/vb/Gift/LiDAR-MOS/sequences/03/velodyne/
posePath: /media/vb/Gift/LiDAR-MOS/sequences/03/poses.txt
# posePath: /home/vb/Documents/public_repositories/SiMpLE/build/lidar_mos_03
startScan: 1
endScan: 500
minRange: 0.5
maxRange: 120
outputFile: false
scanNumsToPrint: []
outputFileName:
outputLabels: true
outputLabelFolder: /home/vb/Documents/PhD/projects/changePointDetectionV7Conc2/results/labels/apollo_03/

# Configuration parameters.
voxelSize: 0.2
occupancySigma: 0.3
freeSigma: 0.3
beliefThreshold: 0.9
convSize: 5
localWindowSize: 3
globalWindowSize: 50
offset: 0