---
# Test setup.
# scanPath: /home/vb/Documents/PhD/datasets/UrbanNav/2020-03-14-16-45-35/
# posePath: /home/vb/Documents/public_repositories/SiMpLE/sampleResults/UrbanNav/simpleOutputs/2020-03-14-16-45-35
scanPath: /home/vb/Documents/PhD/datasets/UrbanNav/2019-04-28-20-58-02/
posePath: /home/vb/Documents/public_repositories/SiMpLE/sampleResults/UrbanNav/simpleOutputs/2019-04-28-20-58-02
startScan: 1
endScan: 1000
minRange: 3
maxRange: 120
outputFile: false
scanNumsToPrint: []
outputFileName:
outputLabels: false
# outputLabelFolder: /home/vb/Documents/PhD/projects/changePointDetectionV7/cpp/results/labels/UrbanNav2020/
outputLabelFolder: /home/vb/Documents/PhD/projects/changePointDetectionV7Conc2/results/labels/UrbanNav2019/

# Configuration parameters.
voxelSize: 0.2
occupancySigma: 0.2
freeSigma: 0.2
beliefThreshold: 0.3
convSize: 5
localWindowSize: 3
globalWindowSize: 300
offset: 0