---
# File paths
scanPath: /media/vb/Gift/DynabloxDataset/corridor_1/scans/
posePath: /media/vb/Gift/DynabloxDataset/corridor_1/test_corridor_1
startScan: 1
endScan: 105
minRange: 0.5
maxRange: 120
outputFile: true
scanNumsToPrint: [99]
outputFileName: /home/vb/Documents/PhD/projects/changePointDetectionV7Conc2/results/test_corridor_1
outputLabels: false
outputLabelFolder: /home/vb/Documents/PhD/projects/changePointDetectionV7Conc2/results/labels/stairs/

# Configuration parameters
voxelSize: 0.2
occupancySigma: 0.2
freeSigma: 0.2
beliefThreshold: 0.9
convSize: 5
localWindowSize: 3
globalWindowSize: 500
offset: 0