---
# Test setup.
scanPath: /media/vb/Gift/kitti-tracking/sequences/19/velodyne/
posePath: /media/vb/Gift/kitti-tracking/sequences/19/poses.txt
startScan: 1
endScan: 1059
minRange: 3
maxRange: 120
outputFile: false
scanNumsToPrint: []
outputFileName:
outputLabels: true
outputLabelFolder: /home/vb/Documents/PhD/projects/changePointDetectionV7Conc2/results/labels/19/

# Configuration parameters.
voxelSize: 0.2
occupancySigma: 0.3
freeSigma: 0.3
beliefThreshold: 0.9
convSize: 5
localWindowSize: 3
globalWindowSize: 300
offset: 0