---
# File paths
scanPath: /media/vb/Gift/DOALS/processed/station/sequence_1/binFiles/
posePath: /home/vb/Documents/public_repositories/SiMpLE/build/seq7_deskewed
startScan: 2
endScan: 2008
minRange: 0.5
maxRange: 120
outputFile: true
scanNumsToPrint: [37, 149, 349, 549, 749, 949, 1149, 1349, 1549, 1749]
outputFileName: /home/vb/Documents/public_repositories/QCD_MOS/results/test_seq7
outputLabels: false
outputLabelFolder: 

# Configuration parameters
voxelSize: 0.2
occupancySigma: 0.2
freeSigma: 0.2
beliefThreshold: 0.3
convSize: 5
localWindowSize: 3
globalWindowSize: 300
offset: 0